/**
 * DE ability path suffixes → Voidforge helminth ability ids.
 * Sourced from wiki Module:InternalNames (display name → allHelminthAbilities).
 * Legacy guessed suffixes kept as fallbacks for older arsenal payloads.
 */
export const HELMINTH_LOTUS_SUFFIX_TO_ID: Record<string, string> = {
  // Helminth-unique (wiki InternalNames)
  HelminthStrengthAbility: "helminth_empower",
  HelminthSpeedAbility: "helminth_infested_mobility",
  HelminthCompanionAbility: "helminth_masters_summons",
  HelminthShieldsAbility: "helminth_rebuild_shields",
  HelminthHackAbility: "helminth_perspicacity",
  HelminthEfficiencyAbility: "helminth_energized_munitions",
  HelminthStunAbility: "helminth_marked_for_death",
  HelminthTreasureAbility: "helminth_golden_instinct",
  // Legacy guessed suffixes (keep as fallbacks)
  HelminthMobilityAbility: "helminth_infested_mobility",
  HelminthSummonAbility: "helminth_masters_summons",
  HelminthShieldAbility: "helminth_rebuild_shields",
  HelminthPerspicacityAbility: "helminth_perspicacity",
  HelminthAmmoAbility: "helminth_energized_munitions",
  HelminthMarkAbility: "helminth_marked_for_death",
  HelminthSonarAbility: "helminth_golden_instinct",

  // Subsumed abilities
  AlchemistVialAbility: "subsume_lavos",
  NullStarAbility: "subsume_nova",
  SilenceAbility: "subsume_banshee",
  BardCharmAbility: "subsume_octavia",
  BerserkerScreamAbility: "subsume_valkyr",
  BrawlerGazeAbility: "subsume_atlas",
  BrokenRotAbility: "subsume_xaku",
  ChoirEyesAbility: "subsume_jade",
  ConcretePillarAbility: "subsume_qorvex",
  RussianRouletteAbility: "subsume_mesa",
  DagathVolleyAbility: "subsume_dagath",
  DevourerConsumeAbility: "subsume_grendel",
  DragonLuckAbility: "subsume_chroma",
  FireBlastAbility: "subsume_ember",
  RadialBlindAbility: "subsume_excalibur",
  FairyDustAbility: "subsume_titania",
  IceSpikeAbility: "subsume_frost",
  FrumentariusCloakAbility: "subsume_cyte_09",
  GarudaSiphonAbility: "subsume_garuda",
  GeodeShardsAbility: "subsume_citrine",
  GlassFragmentAbility: "subsume_gara",
  GyreSphereAbility: "subsume_gyre",
  LightAbility: "subsume_mirage",
  HopliteBashAbility: "subsume_styanax",
  InfestTendrilsAbility: "subsume_nidus",
  InkCloneAbility: "subsume_follie",
  IronFrameStripAbility: "subsume_hildryn",
  MindControlAbility: "subsume_nyx",
  KhoraTwirlAbility: "subsume_khora",
  KoumeiBlockAbility: "subsume_koumei",
  DecoyAbility: "subsume_loki",
  PullAbility: "subsume_mag",
  BanishAbility: "subsume_limbo",
  MonkeyDeathNewAbility: "subsume_wukong",
  TerrorTotemAbility: "subsume_nekros",
  NezhaTrailAbility: "subsume_nezha",
  GlaiveAbility: "subsume_ash",
  NokkoPowerShroomAbility: "subsume_nokko",
  OdaliskDispensaryAbility: "subsume_protea",
  OraxiaEntangleAbility: "subsume_oraxia",
  PacifistWaveAbility: "subsume_baruuk",
  PagemasterDeathAbility: "subsume_dante",
  SmiteAbility: "subsume_oberon",
  PaxTeleportAbility: "subsume_kullervo",
  CannonBarrageAbility: "subsume_hydroid",
  DemonFrameHealAbility: "subsume_uriel",
  PriestCondemnAbility: "subsume_harrow",
  RangerQuiverAbility: "subsume_ivara",
  RevenantAfflictionAbility: "subsume_revenant",
  RhinoRoarAbility: "subsume_rhino",
  RunnerTransferAbility: "subsume_gauss",
  SandmanBlastAbility: "subsume_inaros",
  ShedAbility: "subsume_saryn",
  SentientStompAbility: "subsume_caliban",
  SiriusBuffAbility: "subsume_sirius_orion",
  TempleShredAbility: "subsume_temple",
  TenguBurstAbility: "subsume_zephyr",
  ZapTrapAbility: "subsume_vauban",
  WellOfLifeAbility: "subsume_trinity",
  ShockAbility: "subsume_volt",
  WerewolfLeapAbility: "subsume_voruna",
  WispHarnessAbility: "subsume_wisp",
  WraithGloomAbility: "subsume_sevagoth",
  YareliDisksAbility: "subsume_yareli",
  YinYangTargetAbility: "subsume_equinox",
};
